require: rubocop-rspec
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/development-local.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/EmptyMethod:
  Exclude:
    - 'app/controllers/**/*'
Metrics/MethodLength:
  Exclude:
    - db/**/*
    - spec/**/*
Metrics/AbcSize:
  Exclude:
    - db/**/*
RSpec/ExampleLength:
  Exclude:
  - spec/features/**/*
RSpec/DescribeClass:
  Exclude:
  - spec/features/**/*
RSpec/MultipleExpectations:
  Exclude:
  - spec/features/**/*
